### ISSUE TITLE
RALTB annual chlorophyll verify averages

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbnmc-compliance-assessment-2023#1]
I cannot reproduce the numbers in the [2009 RA Addendum](https://drive.google.com/file/d/10IjJAfcGFf007a5VdPXAUtUi4dx-cmsA/view) nor the [2017-2021 report](https://drive.google.com/file/d/18HHMx4U6vHNrFyepEFuoTJ_sEKyTA_gu/view).  Also verify chlorophyll target (found in former).  

Also need to get data through December, GB indicats Manatee will be available on WIN one month after end of quarter.  Pinellas data in process from SD.

**Comment by esherwoo77** [comment]
As we discussed, the piano roll and compliance assessment table for RLTB should be a direct copy of LTB results. The RLTB compliance end-point relates to maintaining WQ/TMDL conditions in the LTB bay segment. Keeping the BCBS, TCB and MR chlorophyll-a results relative to their NNC is still appropriate (as requested by FDEP).
