### ISSUE TITLE
date displays incorrectly

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/tbnmc-compliance-assessment-2023#3]
https://github.com/tbep-tech/tbnmc-compliance-assessment-2023/blob/6f991b91a9110227a53ef36007e23b5b671b85f2/R/funcs.R#L21

**Comment by fawda123** [comment]
@emseabee just hard-code the date in index.qmd when we're ready to submit to DEP, [here](https://github.com/tbep-tech/tbnmc-compliance-assessment-2023/blob/12855d0b20246e9a634d16cf4e6d9569dea40a53/index.qmd#L16). I was trying to get fancy by having the current date, but it's not worth troubleshooting.
