### ISSUE TITLE
final data for LTB remainder

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/tbnmc-compliance-assessment-2023#5]
lmk when this is ready to send to fdep/usepa. reminding us here so i don't forget.

**Comment by fawda123** [comment]
I've been emailing Greg B about this, last contacted him earlier this month.  They're behind on the data upload to WIN, I checked today and still no data through 2023 (latest is September for Manatee River, August for Terra Ceia).  I'll check again in another week or so.

**Comment by fawda123** [comment]
@emseabee the report is good to go.  Based on Greg's email, it sounded like some of the Q4 data are still missing with no expected submittal date yet.  I think it's incredibly unlikely the data will be available by the June submission deadline.  We got a few more months for TCB and MR with the latest submission, but not 100% complete.
